### ISSUE TITLE
[Feature Request] Show touches when screen recording

### ISSUE THREAD

**Issue by user8446** [you-apps/RecordYou#242]
### Describe your suggested feature

Hi,
 I think it would be an improvement if touches were emphasized when screen recording. 

Currently it is difficult or you can't tell at all what and where it was touched on the screen.

Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by user8446** [comment]
@kik-btaski How does the built-in screen recorder (Android 11 and up) do it for swipes? I don't have swipe capability on my keyboard.

**Comment by user8446** [comment]
Ok some manufacturers remove it and it might not be there with a custom ROM: https://support.google.com/android/answer/9075928?hl=en

Yes I will try one of those keyboards to check the behavior.

**Comment by user8446** [comment]
I tested with FlorisBoard and the built-in screen recorder and it does show the touches as you are glide typing and long presses:


https://github.com/you-apps/RecordYou/assets/18019245/b21a3f24-9739-4c83-b1d1-eb252cce2a6d

**Comment by user8446** [comment]
It does. Anywhere on the screen where you touch it is shows by this circle:

 
![Screenshot 2024-01-11 085107](https://github.com/you-apps/RecordYou/assets/18019245/f0250643-33a2-4264-9074-3efd17c5c66d)

**Comment by user8446** [comment]
It does, it's just not as obvious as the red trace in your video.

Watch the video where I glide type "test". You'll see the circle follow my trace.

**Comment by NilEinne** [comment]
I don't think this is possible via the app at least in stock Android. Yes I know the built-in screen recorder does it, but when I've tested it on my cheap Chinese tablet with Android 13 (so probably little modification), what I've found is it just seems to enable the "show taps" feature in the developer options. The setting goes on when I start recording and goes off when I stop. Further if I turn it off while recording, it stops working in the video too. 

And I don't think normal apps can change this setting. I've tried 2 very popular commercial Android screen recorders and both just tell me to turn on the "show taps" option in developer options since the app cannot do it. So unfortunately you probably have to turn it on in developer options, and then turn it off when done recording if you don't want it all the time.
